[build]
  command = "pnpm install && pnpm build"
  publish = "dist"
  [build.environment]
    NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"